= shell-tester

A little library to create automated tests for shell setups.
When a test is run, it also generates a detailed output of the shell session,
which can be used to create screenshots or videos of the test.

I use this library to xref:dotfiles::index.adoc[test my dotfiles and generate example screenshots for my shell setup].

== Example

[source,js]
.example.js
----
const { ShellTester } = require('shell-tester')
const tester = new ShellTester({ shellCommand: 'sh' }) <1>

tester.session('example', async (s) => { <2>
  await s.expect('$') <3>
  await s.send('ls\r')
  await s.expect('package.json')
})

tester.run() <4>
----
<1> Create a https://github.com/dtinth/shell-tester/blob/main/api/docs/shell-tester.shelltester.md[`ShellTester`] and specify the shell command to use.
<2> Register a test session using the https://github.com/dtinth/shell-tester/blob/main/api/docs/shell-tester.shelltester.session.md[`session`] method.
<3> Automate the shell using the provided https://github.com/dtinth/shell-tester/blob/main/api/docs/shell-tester.shellsession.md[`ShellSession`] object.
<4> Run the registered sessions by calling the https://github.com/dtinth/shell-tester/blob/main/api/docs/shell-tester.shelltester.run.md[`run`] method.

For more detailed examples, see the https://github.com/dtinth/shell-tester/blob/main/test.js[test.js] file.

== Installation

This module is **not versioned** and is **not published on npm**. To install it directly from GitHub, run:

 $ yarn add "dtinth/shell-tester#main"

TIP: To pin the dependency in your `package.json` file and prevent breaking changes from affecting your project, replace `main` with the SHA of the https://github.com/dtinth/shell-tester/commit/main[latest commit].

== Running

The test script can be run directly using Node.js:

 $ node example.js

== Output file

This will generate a file called `tmp/output/example_end.js` in the current directory
which contains the detailed output of the shell session.

A simple HTML viewer can be used to view the output:

 $ echo "file://$PWD/node_modules/shell-tester/preview.html?data=../../tmp/output/example_end.js"

(Open the URL in your browser to see the output.)
