name: CI
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test
      - name: Update API
        run: yarn api
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update generated files
          file_pattern: api/**
          commit_user_name: dtinth-bot
          commit_user_email: dtinth-bot@users.noreply.github.com
          commit_author: dtinth-bot <dtinth-bot@users.noreply.github.com>
